.gitignore, utils/local-engine/Common/DebugUtils.h, utils/local-engine/Shuffle/ShuffleSplitter.cpp, utils/local-engine/tests/gtest_ch_functions.cpp
fix hash value compute error in the hash partitioner
add debug util to print block
=> Fix hash partition error

utils/local-engine/Parser/SerializedPlanParser.cpp
- New Feature
- Improvement
...
=> [CH-18] Supported substrait cast node

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Shuffle/ShuffleSplitter.cpp
=> Fix shuffle column error

utils/local-engine/Common/ExceptionUtils.cpp, utils/local-engine/Common/ExceptionUtils.h, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/local_engine_jni.cpp
add stack trace log on DB::Exception.
=> add stack trace log

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/local_engine_jni.cpp
- New Feature
- Improvement
...
=> Support extract and substring function

utils/local-engine/Common/DebugUtils.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Shuffle/ShuffleSplitter.cpp, utils/local-engine/Storages/SourceFromJavaIter.cpp
add cast function when substrait function output type is different from clickhouse function
fix #23
=> add function result cast

contrib/llvm-cmake/CMakeLists.txt, utils/local-engine/Builder/BroadCastJoinBuilder.cpp, utils/local-engine/Builder/BroadCastJoinBuilder.h, utils/local-engine/CMakeLists.txt, utils/local-engine/Common/JoinHelper.cpp, utils/local-engine/Common/JoinHelper.h, utils/local-engine/Common/Logger.cpp, utils/local-engine/Parser/CHColumnToSparkRow.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Shuffle/NativeWriterInMemory.cpp, utils/local-engine/Shuffle/NativeWriterInMemory.h, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/ShuffleReader.h, utils/local-engine/Storages/InputStreamFileSystem.h, utils/local-engine/Storages/StorageJoinFromReadBuffer.cpp, utils/local-engine/Storages/StorageJoinFromReadBuffer.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/tests/gtest_ch_join.cpp
support broadCast join using storageJoin engine
=> Support broadCast join

utils/local-engine/Shuffle/NativeSplitter.cpp, utils/local-engine/Shuffle/NativeSplitter.h, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/ShuffleReader.h, utils/local-engine/Shuffle/ShuffleWriter.cpp, utils/local-engine/Shuffle/ShuffleWriter.h, utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.cpp, utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.h, utils/local-engine/local_engine_jni.cpp
support shuffle by spark shuffle manager
=> Support new shuffle

utils/local-engine/Storages/StorageMergeTreeFactory.cpp, utils/local-engine/jni_common.h, utils/local-engine/local_engine_jni.cpp
support call init many times
fix memory leak in string conversion
=> fix some issue

utils/local-engine/Common/StringUtils.cpp, utils/local-engine/Common/StringUtils.h, utils/local-engine/Operator/PartitionColumnFillingTransform.cpp, utils/local-engine/Operator/PartitionColumnFillingTransform.h, utils/local-engine/Parser/CHColumnToSparkRow.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Shuffle/NativeSplitter.cpp, utils/local-engine/Storages/SourceFromJavaIter.cpp, utils/local-engine/Storages/SourceFromJavaIter.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/proto/Exprs.proto, utils/local-engine/proto/substrait/algebra.proto, utils/local-engine/proto/substrait/ddl.proto, utils/local-engine/proto/substrait/function.proto, utils/local-engine/proto/substrait/parameterized_types.proto, utils/local-engine/proto/substrait/type.proto, utils/local-engine/tests/gtest_transformer.cpp, utils/local-engine/tests/gtest_utils.cpp
支持nullable属性的数据输入
支持nullable列的列转行
支持parquet分区表
resolves #43
=> Support nullable datatype

utils/local-engine/Parser/CHColumnToSparkRow.cpp
=> support const column in c2r

utils/local-engine/Shuffle/ShuffleSplitter.cpp
修复在nullable类型下进行hash split出错
#56
=> fix columnar shuffle split failed

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/proto/substrait/algebra.proto, utils/local-engine/proto/substrait/capabilities.proto, utils/local-engine/proto/substrait/extensions/extensions.proto, utils/local-engine/proto/substrait/function.proto, utils/local-engine/proto/substrait/parameterized_types.proto, utils/local-engine/proto/substrait/plan.proto, utils/local-engine/proto/substrait/type.proto, utils/local-engine/proto/substrait/type_expressions.proto
- New Feature
- Improvement
...
=> upgrade substrait

utils/local-engine/Common/BlockIterator.cpp, utils/local-engine/Common/BlockIterator.h, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Shuffle/NativeSplitter.cpp, utils/local-engine/Shuffle/NativeSplitter.h, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/ShuffleReader.h, utils/local-engine/Shuffle/ShuffleSplitter.cpp, utils/local-engine/Shuffle/ShuffleSplitter.h, utils/local-engine/local_engine_jni.cpp
=> add BlockIterator to manage memory between java and cpp

utils/local-engine/Builder/BroadCastJoinBuilder.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Storages/StorageJoinFromReadBuffer.h
=> Support expr on broadcast

contrib/arrow-cmake/CMakeLists.txt, utils/local-engine/CMakeLists.txt, utils/local-engine/Common/DebugUtils.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Storages/ArrowParquetBlockInputFormat.cpp, utils/local-engine/Storages/ArrowParquetBlockInputFormat.h, utils/local-engine/Storages/ch_parquet/ArrowColumnToCHColumn.cpp, utils/local-engine/Storages/ch_parquet/ArrowColumnToCHColumn.h, utils/local-engine/Storages/ch_parquet/ParquetBlockInputFormat.cpp, utils/local-engine/Storages/ch_parquet/ParquetBlockInputFormat.h, utils/local-engine/Storages/ch_parquet/arrow/column_reader.cc, utils/local-engine/Storages/ch_parquet/arrow/column_reader.h, utils/local-engine/Storages/ch_parquet/arrow/encoding.cc, utils/local-engine/Storages/ch_parquet/arrow/encoding.h, utils/local-engine/Storages/ch_parquet/arrow/reader.cc, utils/local-engine/Storages/ch_parquet/arrow/reader.h, utils/local-engine/Storages/ch_parquet/arrow/reader_internal.cc, utils/local-engine/Storages/ch_parquet/arrow/reader_internal.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/tests/benchmark_local_engine.cpp, utils/local-engine/tests/gtest_ch_storages.cpp
- New Feature
- Improvement
...
=> Optimize Arrow Parquet Reader (#48)

utils/local-engine/CMakeLists.txt
=> fix compile error

contrib/arrow-cmake/CMakeLists.txt, utils/local-engine/Storages/ch_parquet/ArrowColumnToCHColumn.cpp, utils/local-engine/Storages/ch_parquet/arrow/column_reader.cc, utils/local-engine/Storages/ch_parquet/arrow/encoding.cc, utils/local-engine/Storages/ch_parquet/arrow/encoding.h
- New Feature
- Improvement
...
=> issue #48 fix null value case

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/local_engine_jni.cpp
=> Support expr eval and Support NULL literal

utils/local-engine/Parser/SerializedPlanParser.cpp
- New Feature
- Improvement
...
=> [CH-87] fix min max on date32

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/local_engine_jni.cpp
=> fix aggregate nullable boolean column failed

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
支持使用SingularOrList来表示in函数
resolve #100
=> support singular_or_list

utils/local-engine/Builder/BroadCastJoinBuilder.cpp, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/ShuffleSplitter.cpp, utils/local-engine/Shuffle/ShuffleWriter.cpp
shuffle reader将使用0 columns 0 rows的block作为结束符，shuffle write将不再序列化0 rows block
=>  skip empty block when read shuffle data

utils/local-engine/Parser/SerializedPlanParser.cpp
在filter前删除无用列，只保留输入列和条件列
与 #100 有关
=> remove unused column before filter

utils/local-engine/Parser/SerializedPlanParser.cpp
支持在查询语句中，额外查询常量列，仍不支持直接查询常量例如 select 1 from xxx
=> support select constant

utils/local-engine/Parser/SparkRowToCHColumn.cpp, utils/local-engine/Parser/SparkRowToCHColumn.h, utils/local-engine/tests/testConfig.h.in, utils/local-engine/tool/check-style
- New Feature
- Improvement
...
=> add check style script

utils/local-engine/local_engine_jni.cpp
=> fixed : cover more jni interfaces for catching c++ exceptions

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/jni/jni_error.cpp, utils/local-engine/jni/jni_error.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/tests/benchmark_parquet_read.cpp, utils/local-engine/tool/check-style
- New Feature
- Improvement
...
=> Reduce log output

utils/local-engine/Parser/SparkRowToCHColumn.h, utils/local-engine/Shuffle/NativeSplitter.cpp, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.cpp, utils/local-engine/Storages/SourceFromJavaIter.cpp, utils/local-engine/jni/jni_common.h, utils/local-engine/local_engine_jni.cpp
- Improvement
related to issue #142
=> [fixed #142]catch java exception in c++

utils/local-engine/Common/common.cpp
- Improvement
revert log level to error
=> revert log level to error

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/proto/substrait/algebra.proto
=> support right semi join on substrait

src/Common/CurrentMemoryTracker.cpp, utils/local-engine/Builder/BroadCastJoinBuilder.cpp, utils/local-engine/Builder/BroadCastJoinBuilder.h, utils/local-engine/Common/QueryContext.cpp, utils/local-engine/Common/QueryContext.h, utils/local-engine/jni/ReservationListenerWrapper.cpp, utils/local-engine/jni/ReservationListenerWrapper.h, utils/local-engine/local_engine_jni.cpp
=> [CH-120] Support memory manager

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
support sort operator.
=> [#156]support sort op

src/Common/CurrentMemoryTracker.cpp, utils/local-engine/Common/ConcurrentMap.h, utils/local-engine/Common/QueryContext.cpp, utils/local-engine/jni/ReservationListenerWrapper.cpp, utils/local-engine/jni/ReservationListenerWrapper.h, utils/local-engine/local_engine_jni.cpp
=> [CH-169] add reserve memory no exception

utils/local-engine/Common/JNIUtils.h, utils/local-engine/Parser/SparkRowToCHColumn.h, utils/local-engine/Shuffle/NativeSplitter.cpp, utils/local-engine/Shuffle/ShuffleReader.cpp, utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.cpp, utils/local-engine/Storages/SourceFromJavaIter.cpp, utils/local-engine/jni/ReservationListenerWrapper.cpp
增加宏 get_JNIENV, CLEAN_JNIENV用于获取JNIEnv
=> [CH-176] add micro for jni env

utils/local-engine/Common/QueryContext.cpp
修复内存分配过程中的并发问题
手动测试，运行多轮12线程 tpch100查询，未复现
fix #179
=> [CH-179] fix concurrent problem in allocator

utils/local-engine/Common/CHUtil.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- Improvement
support prewhere on mergetree
=> [CH-184] support prewhere

utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.cpp, utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.h, utils/local-engine/CMakeLists.txt, utils/local-engine/Common/common.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/tests/CMakeLists.txt, utils/local-engine/tests/gtest_local_engine.cpp
- New Feature
- Improvement
...
=> [CH-190] enable tests in GlutenDataFrameAggregateSuite

utils/local-engine/Parser/SerializedPlanParser.cpp
- New Feature
- Improvement
...
=> change any to string value

utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
Support shift left and shift right function. 
=> [CH-215] Support shift left and shift right function. 

utils/local-engine/Parser/SerializedPlanParser.cpp
- New Feature
Fix faild CH uts in https://github.com/oap-project/gluten/pull/620
Effected functions: 
- extract(QUARTER from xx)
- extract(WEEK from xx)
- extract(SECOND from xx)
=> [OPPRO-330] Fix faild CH uts in https://github.com/oap-project/gluten/pull/620

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
Support condition expressions, close https://github.com/Kyligence/ClickHouse/issues/202
=> [CH-202] Support condition expression, include if/else and case/when

src/Functions/IFunction.cpp, src/Functions/IFunction.h, src/Functions/array/arrayElement.cpp, src/Interpreters/ActionsDAG.cpp, utils/local-engine/Common/DebugUtils.cpp, utils/local-engine/Common/DebugUtils.h, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
- support map[key] and array[index] expression
- some compatiable changes to make sure transforming from substrait map/array functions to ch working.
=> [CH-212] support map[key] and array[index] expression && solve map/array nullable compatiability issue

utils/local-engine/Storages/StorageMergeTreeFactory.cpp
=> [242] Fixed a data racing bug

utils/local-engine/Parser/RelParser.cpp, utils/local-engine/Parser/RelParser.h, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Parser/SortRelParser.cpp, utils/local-engine/Parser/SortRelParser.h, utils/local-engine/Parser/WindowRelParser.cpp, utils/local-engine/Parser/WindowRelParser.h, utils/local-engine/local_engine_jni.cpp, utils/local-engine/proto/substrait/algebra.proto
- New Feature
...
Support window function
=> [218] Support  window function

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Parser/SortRelParser.cpp, utils/local-engine/Parser/SortRelParser.h
=> [245]Optimization for `order by xxx limit xxx` 

utils/local-engine/Parser/SparkRowToCHColumn.cpp
Changelog category:
fix cast error when type is nullable
=> [CH-253]Fix nullable struct/array/map cast error

utils/local-engine/Common/CHUtil.cpp, utils/local-engine/Common/CHUtil.h, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Storages/SubstraitSource/OrcFormatFile.cpp, utils/local-engine/Storages/SubstraitSource/OrcFormatFile.h, utils/local-engine/Storages/SubstraitSource/OrcUtil.cpp, utils/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp, utils/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp, utils/local-engine/Storages/SubstraitSource/SubstraitFileSource.h, utils/local-engine/Storages/ch_parquet/OptimizedArrowColumnToCHColumn.cpp, utils/local-engine/Storages/ch_parquet/OptimizedParquetBlockInputFormat.cpp
=> [239]Support queries on struct fields

utils/local-engine/Parser/SparkRowToCHColumn.cpp, utils/local-engine/Parser/SparkRowToCHColumn.h
- Bug Fix (user-visible misbehaviour in official stable)
...
Closes https://github.com/Kyligence/ClickHouse/issues/259.
=> [CH-259]fixed a bug related to count(1)/count(*)

utils/local-engine/Parser/SerializedPlanParser.cpp
- Bug Fix
Fix inset is empty return logic erro, cause by spark-29100.
When inset is empty, always return false.
test by gluten  ut
=> [Gluten-826]fix Inset is empty

utils/local-engine/Parser/SerializedPlanParser.h
support base64&&unbase64 functions
run  GlutenStringExpressionsSuite
=> [Gluten-867] support base64&&unbase64 functions

utils/local-engine/Builder/SerializedPlanBuilder.cpp, utils/local-engine/Parser/CHColumnToSparkRow.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/proto/substrait/type.proto
- New Feature
Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232
=> [CH-232] Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232

utils/local-engine/proto/substrait/algebra.proto, utils/local-engine/proto/substrait/plan.proto
- New Feature
Update substrait proto by velox
test this please with 898
=> [Gluten-898]Update substrait proto

utils/local-engine/Operator/ExpandStep.cpp, utils/local-engine/Operator/ExpandStep.h, utils/local-engine/Operator/ExpandTransform.cpp, utils/local-engine/Operator/ExpandTransorm.h, utils/local-engine/Parser/ExpandRelParser.cpp, utils/local-engine/Parser/ExpandRelParser.h, utils/local-engine/Parser/RelParser.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Storages/SourceFromJavaIter.cpp
- New Feature
...
Offload `CustomExpand ` into `ClickHouse` to support grouping sets.
=> [250] Support grouping sets

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
...
follows up https://github.com/Kyligence/ClickHouse/issues/261
following functions are supported
- get_json_object
- to_json
- from_json
Closes https://github.com/oap-project/gluten/issues/853
=> Support more json functions

utils/local-engine/Common/common.cpp
- New Feature
sync timezone to backend
test by gluten ut
=> [Gluten-926]sync timezone to backend

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
part1: support function md5/lpad/rpad/reverse
=> [CH-278] part1: support function md5/lpad/rpad/reverse

utils/local-engine/Parser/RelParser.h, utils/local-engine/Parser/WindowRelParser.cpp, utils/local-engine/Parser/WindowRelParser.h
...
follows up https://github.com/Kyligence/ClickHouse/issues/283
=> fixed: count(1)/sum(1) on window

utils/local-engine/Common/CHUtil.cpp, utils/local-engine/Common/CHUtil.h, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h, utils/local-engine/Storages/SourceFromJavaIter.cpp
- New Feature
...
followup https://github.com/Kyligence/ClickHouse/issues/261
new functions:
-  named_struct
- element_at
- array_contains
- map_keys
- map_values
=> Support more array/map/struction functions

utils/local-engine/Parser/RelParser.cpp, utils/local-engine/Parser/RelParser.h, utils/local-engine/Parser/WindowRelParser.cpp, utils/local-engine/Parser/WindowRelParser.h
- New Feature
...
new window functions
- lead
- lag
- first_value
- last_value
follows up https://github.com/Kyligence/ClickHouse/issues/261
=> Support more window functions

utils/local-engine/Parser/CHColumnToSparkRow.cpp
=> fix write array failed

utils/local-engine/Storages/ArrowParquetBlockInputFormat.cpp
- Bug Fix
Fix read empty parquet cause core dump
=> [CH-306]Fix read empty parquet

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
Support repeat function , as described in issue: https://github.com/Kyligence/ClickHouse/issues/297
...
=> Support repeat function

utils/local-engine/Parser/RelParser.cpp, utils/local-engine/Parser/RelParser.h, utils/local-engine/Parser/WindowRelParser.cpp, utils/local-engine/Parser/WindowRelParser.h
=> support lead/lag/dense_rank

utils/local-engine/proto/substrait/algebra.proto, utils/local-engine/proto/substrait/extended_expression.proto
Upgrade substrait proto by velox.
test by glutenut
=> [VL-1004]Upgrade substrait proto by velox

utils/local-engine/Parser/SerializedPlanParser.h
=> [CH-325]Support `stddev_samp`

utils/local-engine/Parser/SerializedPlanParser.cpp
fix substrait parser for the case when filter condition has only one singular_or_list
=> [CH-349]fix substrait parser to support some singular_or_list cases

utils/local-engine/Common/CHUtil.cpp, utils/local-engine/Common/CHUtil.h, utils/local-engine/Parser/SerializedPlanParser.cpp
- Improvement
Print pipeline with block header, makes it easier to debug. Closes https://github.com/issues
=> [CH-355] print pipeline if log level is debug

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
related issue: [issue-328](https://github.com/Kyligence/ClickHouse/issues/328)
=> [CH-328] support function isNaN

utils/local-engine/Common/common.cpp, utils/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
Fix the bug that libhdfs config is not correctly set
This close #359
=> [CH-359] fix libhdfs3 conf not correctly set bug

utils/local-engine/Shuffle/ShuffleSplitter.cpp, utils/local-engine/Shuffle/ShuffleSplitter.h, utils/local-engine/local_engine_jni.cpp
- Improvement
see issue: [issue-353](https://github.com/Kyligence/ClickHouse/issues/353)
=> [CH-353] ShuffleSplitter improvement

utils/local-engine/Operator/ExpandStep.cpp, utils/local-engine/Operator/ExpandTransform.cpp
=> [CH-375] Fix create nullable column used ColumnInt8

utils/local-engine/Parser/SparkRowToCHColumn.cpp
=> Fix convert empty string to null

utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
Support function space
``` sql
SELECT space(3);
```
Result:
``` text
┌─space(3) ────┐
│              │
└──────────────┘
```
=> Support function space

utils/local-engine/jni/jni_common.h
=> [394]Print exception message

utils/local-engine/Common/CHUtil.cpp, utils/local-engine/Functions/registerFunctions.cpp, utils/local-engine/Functions/reinterpretAsStringSpark.cpp, utils/local-engine/Parser/SerializedPlanParser.cpp, utils/local-engine/Parser/SerializedPlanParser.h
fix bugs of length and cast(x as binary), close  https://github.com/Kyligence/ClickHouse/issues/413
=> [CH-413] implement function reinterpretAsStringSpark and fix bugs of length(binary)/cast(x as binary)

utils/local-engine/Parser/CHColumnToSparkRow.cpp
Fix NPE caused by CHColumnToSparkRow when converting map field, close #422
=> [CH-422] Fix NPE caused by CHColumnToSparkRow when converting map field

contrib/aws-cmake/CMakeLists.txt, src/IO/S3/Client.cpp, src/IO/S3/Credentials.h
- New Feature
- Improvement
...
=> support assume role (bug fix included)

src/DataTypes/NestedUtils.cpp
close issues: https://github.com/oap-project/gluten/issues/2463 and https://github.com/oap-project/gluten/issues/2459
=> [GLUTEN-2463][CH] Allow nullable tuple column as input in Nested::flatten

src/Processors/Formats/Impl/ORCBlockOutputFormat.cpp
Fix https://github.com/oap-project/gluten/issues/2584
=> [GLUTEN-2584][CH] Fix mismatch complex type values during native orc writing

.gitignore, CMakeLists.txt
- New Feature
- Improvement
...
=> add cmake flags to avoid unkown stack in flume graph

src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp
- Improvement
Support nullable complex types for native orc input format
=> [GLUTEN-3115] Support nullable complex types for new native orc input format

src/Interpreters/BloomFilter.h
- New Feature
- Improvement
...
=> [Gluten-3187][CH] expose Bloom filter params

src/Functions/FunctionsConversion.h
- Improvement
Fix parse float string to int
=> Fix parse float string to int

src/Functions/array/arrayElement.cpp, tests/performance/array_element.xml
Optimize array element function when input is array(map)/array(array(string))/array(array(number)).  close https://github.com/oap-project/gluten/issues/3927
Let's merge it into Kyligence/ClickHouse since https://github.com/ClickHouse/ClickHouse/pull/56403 had been blocked for a month.
=> [GLUTEN-3927][CH] Optimize array element function when input is array(map)/array(array(string))/array(array(number))

.gitmodules, contrib/CMakeLists.txt, contrib/libmaxminddb-cmake/CMakeLists.txt, contrib/libmaxminddb-cmake/maxminddb_config.h.in, src/CMakeLists.txt, src/Common/config.h.in, src/configure_config.cmake
=> [GLUTEN-3953] [CH] Add contrib mmdb

.gitmodules, contrib/CMakeLists.txt, contrib/libmaxminddb-cmake/CMakeLists.txt, contrib/libmaxminddb-cmake/maxminddb_config.h.in, src/CMakeLists.txt, src/Common/config.h.in, src/configure_config.cmake
=> [GLUTEN-3953] [CH] Add contrib mmdb 

src/Interpreters/Aggregator.h
- New Feature
...
used in https://github.com/oap-project/gluten/pull/4179
=> Add `GlutenAggregatorUtil` to expose APIs into gluten

src/Interpreters/Aggregator.h
- New Feature
...
used in https://github.com/oap-project/gluten/pull/4179
=> Add GlutenAggregatorUtil to expose APIs into gluten

src/Interpreters/ActionsDAG.cpp
Fix issue of actions dag split. Close https://github.com/oap-project/gluten/issues/4723
=> [GLUTEN-4723]Fix issue of actions dag split

src/Disks/ObjectStorages/HDFS/HDFSObjectStorage.h
Used by https://github.com/apache/incubator-gluten/pull/4676
=> make HDFSObjectStorage members protected

contrib/sparse-checkout/update-aws.sh, contrib/sparse-checkout/update-boost.sh, src/Disks/ObjectStorages/Cached/registerDiskCache.cpp, src/Disks/ObjectStorages/HDFS/HDFSObjectStorage.h
- New Feature
- Improvement
...
=> Support MergeTree Write On Object Storage

src/Functions/FunctionDateOrDateTimeAddInterval.h
Relation to issue https://github.com/apache/incubator-gluten/issues/4989
=> Fix timestampadd datetime64

src/Common/CurrentMemoryTracker.cpp, src/Common/CurrentMemoryTracker.h
For monitor current spark thread offheap memory.
=> [GLUTEN-5476] Add current_memory function ref

contrib/sparse-checkout/update-aws.sh, contrib/sparse-checkout/update-boost.sh, src/Disks/ObjectStorages/Cached/registerDiskCache.cpp, src/Processors/QueryPlan/SortingStep.cpp, src/Processors/QueryPlan/SortingStep.h, src/Processors/Transforms/MergeSortingTransform.cpp, src/Processors/Transforms/MergeSortingTransform.h, src/Processors/Transforms/SortingTransform.h
- New Feature
- Improvement
...
=> Optimize sort spill

src/DataTypes/DataTypeArray.cpp
Fix get dimension error when nullable type in array
=> Fix get dimension error when nullable type in array

src/Disks/IO/ReadBufferFromRemoteFSGather.cpp, src/Disks/ObjectStorages/AzureBlobStorage/AzureObjectStorage.cpp, src/Disks/ObjectStorages/DiskObjectStorageMetadata.cpp, src/Disks/ObjectStorages/DiskObjectStorageMetadata.h, src/Disks/ObjectStorages/HDFS/HDFSObjectStorage.cpp, src/Disks/ObjectStorages/IObjectStorage.h, src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp, src/Disks/ObjectStorages/S3/S3ObjectStorage.cpp, src/Disks/ObjectStorages/StoredObject.h
=> Support merge MergeTree files

src/Columns/IColumn.cpp
- New Feature
- Improvement
...
=> [GLUTEN-6583] Bug in serializing complicated types with nested nulls

src/Processors/Formats/Impl/ORCBlockOutputFormat.cpp
Fix mismatch between written struct column which contains null and orc file content. Close https://github.com/apache/incubator-gluten/issues/8032
=> [GLUTEN-8032] Fix mismatch between written struct column which contains null and ORC file content

src/Core/AccurateComparison.h, src/Core/CompareHelper.h
- Improvement
https://spark.apache.org/docs/3.5.3/sql-ref-datatypes.html#nan-semantics
=> Use Spark NaN semantics

src/Functions/FunctionsConversion.h
- New Feature
- Improvement
...
=> Patch for converting nullable(nothing) to non-nullable type
