Kyligence/ClickHouse

- src/Processors/ISimpleTransform.cpp
- src/Processors/ISimpleTransform.h
- src/Processors/ISource.cpp
- src/Processors/ISource.h
This reverts commit 69a445fb0a84e36d083be7463d7d005f309baeb3.
> Revert "add time print in transform"

- src/Interpreters/TableJoin.h
- utils/local-engine/Common/DebugUtils.cpp
- utils/local-engine/Common/common.cpp
- utils/local-engine/Parser/SerializedPlanParser.cpp
当join类型为left join时，右表需要转换为nullable的类型。
通过在join之后增加filter算子临时支持join的on condition，当join为left join时数据存在问题，后续需要修改为on clause的实现
> fix join use nulls and support post join filter

- utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.cpp
- utils/local-engine/local_engine_jni.cpp
- New Feature
- Improvement
...
> Using NewWeakGlobalRef instead of NewGlobalRef

- utils/local-engine/Parser/SerializedPlanParser.cpp
修复了当连续join同一张表时，会存在列重名的问题导致结果错误。
> fix join duplicate table error

- utils/local-engine/Parser/SerializedPlanParser.cpp
- New Feature
use one SingularOrList.options to indicate one value for the `in` expression.
...
> [CH-129][Followup] Support substrait SingularOrList

- utils/local-engine/Parser/SparkRowToCHColumn.cpp
- utils/local-engine/Parser/SparkRowToCHColumn.h
- utils/local-engine/local_engine_jni.cpp
improve the performance of converting row to column by reducing jvm calls
The overhead of java method call from jni is high. In converting a row batch into column batch, the total java call cost could reach almost halft of total time.
In this pr, we try to reduce the java calls from jni. `SparkRowIterator` has a new interface `nextBatch`, it will return a batch of rows instead of one row. And this make a significant improvement.
We run the following query (We disable the filter operator transform here).
```SQL
select count(msgtype) from (select appid + 1 as appid, msgtype,rtime  from test_table where msgtype = 14) as t;
```
use …
> improve the performance of converting row batch to column batch

- utils/local-engine/Parser/SparkRowToCHColumn.cpp
- utils/local-engine/Parser/SparkRowToCHColumn.h
- utils/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
the required columns could be empty in spark plan, and cause a coredump in SparkRowToCHColumn
When there is no required columns in a row batch, we try to an anonymous const column in the result block of `SparkRowToCHColumn`. This could happend in some cases. E.g count(*)
This doesn't break the execution
> fixed a bug: coredump caused by transform a row batch with empty required columns into `DB::Block`

- utils/local-engine/Common/CHUtil.cpp
- utils/local-engine/Common/CHUtil.h
- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
- utils/local-engine/Storages/SourceFromJavaIter.cpp
- utils/local-engine/Storages/SourceFromJavaIter.h
- utils/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
support count(*)/count(1)
- New Feature
relate to issue https://github.com/Kyligence/ClickHouse/issues/45
Read from file sources or java batch iterator will fail with empty columns to read. This happends when running the following queries.
```SQL
select count(1) from t;
select sum(1) from t;
select 1 from t;
```
In this case, the rows number is the only information to need. To solve this, we try to build a block with an virtual column which indicates the rows number, and this virtual column will not be really used.
In `SubstraitFileSource`, if the file implement `getTotalRows`, we build blocks with a constant column whose total size is equal to `getTotalRows`'s …
> [CH-45]support count(*/count(1)

- utils/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
Support non-HA mode for ClickHouse reading from HDFS.
Close #180 .
- New Feature
- Improvement
...
> [CH-180] Support non-HA mode for ClickHouse reading from HDFS

- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
- Improvement
Implement strings functions between spark and clickhouse: ascii/concat/instr/char_length/replace/split, which close https://github.com/Kyligence/ClickHouse/issues/170
```
0: jdbc:hive2://localhost:10000/> explain formatted select concat(l_shipinstruct, l_shipmode) from lineitem limit 10; 
+----------------------------------------------------+
|                        plan                        |
+----------------------------------------------------+
| == Physical Plan ==
CollectLimit (5)
+- CHNativeColumnarToRow (4)
+- * ProjectExecTransformer (2)
+- * Scan parquet  (1)
(1) Scan parquet 
Output [2]: [l_shipinstruct#162, l_shipmode#163]
Batched: true …
```
> [CH-170] Implement strings functions between spark and clickhouse: concat/instr/char_length/replace/abs/chr/ceil/floor/exp/power

- utils/local-engine/Common/Logger.h
- utils/local-engine/Parser/CHColumnToSparkRow.cpp
close https://github.com/Kyligence/ClickHouse/issues/197 
TODO 
- improve c2r performance when column is const
> [CH-197] Fix bug when c2r with const columns

- utils/local-engine/Parser/SparkRowToCHColumn.h
close https://github.com/Kyligence/ClickHouse/issues/199, introduced in pr: https://github.com/Kyligence/ClickHouse/pull/143
> [CH-199] Fix bug of "select cos(0)" returning no rows

- utils/local-engine/Storages/ArrowParquetBlockInputFormat.cpp
- utils/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
add format settings for parsing parquet files.
enable `use_lowercase_column_name` in parsing parquet files.
> [CH-206] Add format settings for parsing parquet files

- utils/local-engine/Common/common.cpp
`loadSettingsFromConfig ` seems has a bug for checking path exists.
> [CH-204] Fixed a bug in initializing settings

- utils/local-engine/Storages/SubstraitSource/FormatFile.h
- utils/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- utils/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
Improve: reducing the open operation for the same file when reading parquet files
> Improve: reducing the open operation for the same file when reading parquet files

- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
- Improvement
...
> Add spark check_overflow function and cast toDecimal32/64/128

- utils/local-engine/Builder/BroadCastJoinBuilder.cpp
- utils/local-engine/Builder/BroadCastJoinBuilder.h
- utils/local-engine/Shuffle/ShuffleReader.cpp
- utils/local-engine/Shuffle/ShuffleReader.h
- utils/local-engine/Shuffle/ShuffleSplitter.cpp
- utils/local-engine/Shuffle/ShuffleSplitter.h
- utils/local-engine/Shuffle/ShuffleWriter.cpp
- utils/local-engine/Shuffle/ShuffleWriter.h
- utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.cpp
- utils/local-engine/Shuffle/WriteBufferFromJavaOutputStream.h
- utils/local-engine/local_engine_jni.cpp
- utils/local-engine/tests/benchmark_local_engine.cpp
Skip memory copy between onheap and native when using columnar shuffle manager.
...
> [CH-262] Skip memory copy between onheap and native when using columnar shuffle manager

- utils/local-engine/Parser/SerializedPlanParser.cpp
In clickhouse
```sql
// return false
select 1 in (2, null);
```
Spark return `null`, and fix it
> [Gluten-860]fix insert function result not correct

- utils/local-engine/Shuffle/NativeSplitter.cpp
- utils/local-engine/Shuffle/SelectorBuilder.cpp
- utils/local-engine/Shuffle/SelectorBuilder.h
- utils/local-engine/Shuffle/ShuffleSplitter.cpp
- utils/local-engine/Shuffle/ShuffleSplitter.h
- utils/local-engine/local_engine_jni.cpp
- Bug Fix
#272 
When `block.findByName` is null, will use `getByPosition` instead of name
> [CH-272]Fix union join error

- utils/local-engine/jni/jni_common.h
> [304] Print jvm stacktrace when the exception is caught in C++

- utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.h
fix the bug that multi aggregation fail due to mistake serializing partial aggregation with aggregation in shuffle
> [CH-300] fix multi aggregation fail due to serialize partial aggregation to aggregation in shuffle

- utils/local-engine/Builder/BroadCastJoinBuilder.cpp
When executing BHJ, there are some JVM Object not to be GC and lead to memory leak.
- New Feature
- Improvement
...
> [CH-316] Fix memory leak when executing BHJ

- utils/local-engine/Parser/CHColumnToSparkRow.cpp
Fix bug when struct contains decimal types. It is found in pr: https://github.com/oap-project/gluten/pull/897
```
CREATE TEMPORARY VIEW nation
USING org.apache.spark.sql.parquet
OPTIONS (
path  "/data1/liyang/cppproject/gluten/gluten-core/src/test/resources/tpch-data/nation"
) ;
select n_nationkey, named_struct("a", n_nationkey, "b", n_regionkey, "c", 2.0) as t from nation; 
```
> Fix bug when struct contains decimal types

- utils/local-engine/Parser/CHColumnToSparkRow.cpp
- utils/local-engine/Parser/CHColumnToSparkRow.h
- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SparkRowToCHColumn.cpp
Substrait plan decimal is Little-endian and unsaferow is Big-endian.
- Bug Fix 
test by sql
```sql
SELECT
cast(1.11 as decimal(20, 3)),
cast(1.123456789 as decimal(20,9)),
cast(123456789.123456789 as decimal(30,9)),
cast(1.12345678901234567890123456789 as decimal(38,29)),
cast(123456789.123456789012345678901234567 as decimal(38,27))
```
Clickhouse中Decimal128是用的wide_integer表示
wide_integer由1个长度为2的Int128(原始类型为int64)数组表示，sizeof(Decimal128)=16
大致表示为
Decimal.value.items
Decimal.value<wide::integer<Int128,int>>.items<wide::integer<Int128,int>::base_type[2]>
Item[0]表示低位，Item[1]表示高位置
以下是一个类型为Decimal128(38, 18)，值为123456789.123456789012345678901234567的表示法
Item[0]=17502027876307000320    低位
item[1]=6692605                               高位
17502027876307000320的地址上数据为 00 5c 43 b0   9f b1 e3 f2，左边低位 …
> Fix decimal128 value error

- utils/local-engine/local_engine_jni.cpp
- utils/local-engine/tests/benchmark_local_engine.cpp
- utils/local-engine/tests/benchmark_spark_row.cpp
- utils/local-engine/tests/gtest_local_engine.cpp
Fix some asan complain about inside_main
```
=================================================================
==18419==ERROR: AddressSanitizer: odr-violation (0x0000142a1940):
[1] size=1 'inside_main' /data1/liyang/cppproject/kyli/ClickHouse/utils/local-engine/tests/gtest_local_engine.cpp:89:6
[2] size=1 'inside_main' /data1/liyang/cppproject/kyli/ClickHouse/utils/local-engine/local_engine_jni.cpp:30:6
These globals were registered at these points:
[1]:
==18419==WARNING: invalid path to external symbolizer!
==18419==WARNING: Failed to use and restart external symbolizer!
#0 0x2eac3fd (/data6/liyang/spark-3.2.2-bin-hadoop3.2/liyang/unit_tests_local_engine+0x2eac3fd)
#1 0x30392be (/data6/liyang/spark-3.2.2-bin-hadoop3.2/liyang/unit_tests_local_engine+0x …
```
> Fix some asan complain about inside_main

- utils/local-engine/Storages/ch_parquet/arrow/column_reader.cc
Fix coredump caused by CHByteArrayChunkedRecordReader, closes https://github.com/Kyligence/ClickHouse/issues/369
> [CH-369] Fix coredump caused by CHByteArrayChunkedRecordReader 

- utils/local-engine/Parser/SparkRowToCHColumn.cpp
Fix the bug that it may throw bad_alloc exception when converting spark rows to ch column
This pr close #362 .
> [CH-362] fix bad_alloc when converting spark rows to ch column

- utils/local-engine/Functions/positionUTF8Spark.cpp
- utils/local-engine/Functions/registerFunctions.cpp
- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
related issue : [issue-313](https://github.com/Kyligence/ClickHouse/issues/313)
> [CH-313] support functions position/locate

- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
Support full join with join condition.
test by spark ut
> Support full join with join condition

- utils/local-engine/Parser/SerializedPlanParser.cpp
Velox resize checkoverflow function args to 3.
Fix it.
> [VL] Support Decimal type in Gluten

- utils/local-engine/Common/common.cpp
Fix error caused by case-sensitive matching of ORC/Parquet, like Column 'deviceid' is not presented in input data
> [CH-387] Fix error caused by case-sensitive matching of ORC/Parquet, like Column 'deviceid' is not presented in input data

- utils/local-engine/Parser/SerializedPlanParser.cpp
Fix join key with alpha ASCII will accured `assert`
```sql
select * from
(select l_partkey as `中文` from lineitem where l_partkey='6731') t1
full join
(select l_partkey `中文`,l_shipinstruct from lineitem where l_partkey='6731') t2
on t1.`中文`=t2.`中文`
```
test by gluten ut
> Fix join key with alpha ASCII

- utils/local-engine/Parser/SerializedPlanParser.cpp
> [CH-383] Fix 'Unknown identifier' exception

- utils/local-engine/Shuffle/NativeSplitter.cpp
- utils/local-engine/Shuffle/NativeSplitter.h
- utils/local-engine/Shuffle/SelectorBuilder.cpp
- utils/local-engine/Shuffle/SelectorBuilder.h
- utils/local-engine/Shuffle/ShuffleSplitter.cpp
- utils/local-engine/Shuffle/ShuffleSplitter.h
- utils/local-engine/local_engine_jni.cpp
- Improvement
...
Support partitioning with expressions. Also aband the old way in `RangePartitioning` to support expressions.
close https://github.com/Kyligence/ClickHouse/issues/323
> [326] Support partitioning with expressions

- utils/local-engine/Shuffle/NativeSplitter.cpp
The buffer size of ColumnBuffer is now hard code to 8192, let it be the same as Option.buffer_size.
> fix size of ColumnBuffer not configurable

- utils/local-engine/Shuffle/SelectorBuilder.cpp
- Bug Fix
Since `cityHash64` will be null if any argument is null, this could cause data skew. Remove the codes for marking null rows to belong to partition 0, we still keep the result correct. 
...
close #405
> [405] Eliminate data skew in hash shuffle

- utils/local-engine/Parser/CHColumnToSparkRow.cpp
- utils/local-engine/Parser/CHColumnToSparkRow.h
- utils/local-engine/Parser/SerializedPlanParser.cpp
- utils/local-engine/Parser/SerializedPlanParser.h
- New Feature
Implement json_tuple funtion by use JSONExtract function in ck, the releated issue: https://github.com/Kyligence/ClickHouse/issues/358
1. convert json_tuple to JSONExtract function;
2. convert json_tuple result to multi columns likes spark json_tuple
> [CH-358]Support json_tuple function

- src/AggregateFunctions/AggregateFunctionGroupArray.cpp
> [398]Fixed: `groupArray`'s result could be null

- src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp
- Improvement
Close https://github.com/oap-project/gluten/issues/1914 
原来的实现：当将arrow column转化为ch column时，如果arrow type是负责类型(list/map/struct), 则不抽取arrow column的null map, 因为ch中复杂类型都是非nullable的。
现在的实现：为了保持与gluten兼容，即允许复杂类型为nullable, 修改代码，使得arrow type为复杂类型时，依然抽取null map和data column, 构成对应ch的nullable column
> [GLUTEN-1914] Allow nullable complex type when convert arrow column to ch column. 

- src/Processors/Formats/Impl/CHColumnToArrowColumn.cpp
- Improvement
Allow nullable complex types when writing into parquet/orc
> Allow nullable complex types when writing into parquet/orc

- src/Functions/array/arrayElement.cpp
Bug fix
Bug fix problem described in: https://github.com/oap-project/gluten/issues/2582
While use array<struct> as filter, like `select * from table where data[0].a = 1`,  it will use `arrayElement` function to do its filter action,  and go to #perform#executeTuple at arrayElement.cpp, which will return directly, and not init sink to builder.
and the `sink_null_map_holder` in builder not init, still is a nullptr, the left procedure will transform on this nullptr, and cause crash.
> [GLUTEN-2582][CH]Bug fix array struct crash problem

- src/DataTypes/getLeastSupertype.cpp
- src/DataTypes/tests/gtest_data_type_get_common_type.cpp
- Improvement
Support nullable complex types in getLeastSupertype. close https://github.com/oap-project/gluten/issues/2340
> [GLUTEN-2340][CH] Support nullable complex types in getLeastSupertype

- src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp
- Improvement
Skip map field with complex key type when reading schema from orc files. This change could avoid failed uts under package `org.apache.spark.sql.execution.datasources.orc`
> [GLUTEN-3137] Skip map field with complex key type when reading schema from orc files

- src/Columns/ColumnNullable.cpp
- Improvement
The problem is described in issue https://github.com/oap-project/gluten/issues/3908, the memcmp in `ColumnNullable`'s function `insertRangeSelective` will decrease the shuffle write performance, and after remove the `memcmp` logical, the shuffle write performance improve as described in pr https://github.com/oap-project/gluten/pull/3909
> [GLUTEN-3908][CH]Improve insert range selective  for column nullable

- src/Core/Settings.h
- src/Formats/FormatFactory.cpp
- src/Formats/FormatSettings.h
- src/Processors/Formats/Impl/CSVRowInputFormat.cpp
- Improvement
Fix problems as described in https://github.com/ClickHouse/ClickHouse/pull/58225 
While deserialize csv input, if we set the config `input_format_csv_empty_as_default = true`, which would set default value to field if the input is empty, and this is also take effect for Nullable(String) type, in this case, if the input is a empty string,  then the field will be set default value as `NULL`,  as show below
Here it is not suitable，to set `NULL` when the input is empty for `Nullable(String)` type, and it is better to set a empty string for the field.
> Fix input empty as default for nullable string field in CSV InputFormat

- src/Processors/QueryPlan/ReadFromMergeTree.h
Move api `ReadFromMergeTree::AnalysisResult getAnalysisResult() const;` to public in the class `ReadFromMergeTree`
(cherry picked from commit 564c798ae2db41f161aaf8988091fa5bf6659457)
- New Feature
- Improvement
...
> [GLUTEN-4454][CH] Support write mergetree data for CH backend

- src/Disks/ObjectStorages/HDFS/HDFSObjectStorage.h
- New Feature
- Improvement
...
> make HDFSObjectStorage members protected

- src/AggregateFunctions/AggregateFunctionSum.cpp
- src/AggregateFunctions/AggregateFunctionSum.h
- New Feature
Difference between sum and sum0:
If agg data is empty, sum(nullable_col) return \N, but sum0 return 0.
which code take effect:
```
AggregateFunctionProperties properties = { .returns_default_when_only_null = true, .is_order_dependent = false }
```
ClickHouse plan difference:
> Support sum0 function

- src/Core/DecimalFunctions.h
Allow overflow when converting decimal to int like spark
> [GLUTEN-6016] Allow overflow when converting decimal to int like spark

- src/Functions/concat.cpp
- Improvement
Allow concat process Nullable(Array(T)) or Nullable(Map(K, V)) or Nullable(Tuple(T1, T2...))
> [GLUTEN-6977] Allow concat process Nullable(Array(T)) or Nullable(Map(K, V)) or Nullable(Tuple(T1, T2...))

- src/Interpreters/HashJoin/HashJoin.cpp
- New Feature
- Improvement
This is not issue could happen in CH, we fix it here
related PR https://github.com/apache/incubator-gluten/pull/7083
> [GLUTEN-7077] `have_compressed` is lost in `HashJoin::reuseJoinedData`

- src/Core/Settings.h
- src/Functions/FunctionsConversion.cpp
- src/IO/WriteHelpers.h
- src/IO/tests/gtest_DateTimeToString.cpp
Output scale is dynamic in (0, 3, 6) according to real scale. See changes in following examples.
1. 2012-01-01 00:11:22.000000 -> 2012-01-01 00:11:22
2. 2012-01-01 00:11:22.120000 -> 2012-01-01 00:11:22.120
3. 2012-01-01 00:11:22.123400 -> 2012-01-01 00:11:22.123400
> Rewrite datetime64 format logic. 

- src/Functions/array/arrayElement.cpp
- Improvement
Fix incompatiability about array(tuple) and array(tuple) as argument in function arrayElementOrNull. Thus failed uts in https://github.com/apache/incubator-gluten/pull/7242 "test parquet push down filter with multi-nested column types" could be fixed.
> [GLUTEN-7240] Fix incompatiability about array(tuple) and array(tuple) as argument in function arrayElementOrNull

- src/Interpreters/Aggregator.cpp
Fix https://github.com/apache/incubator-gluten/issues/7311
...
> [GLUTEN-7311]A patch for supporting multiple aggregate phases in one step

- src/IO/ParallelReadBuffer.cpp
- src/IO/ParallelReadBuffer.h
Enable parallel downloading for text and json.
> [GLUTEN-7387][CH] Enable parallel downloading for text and json

- src/Processors/Formats/Impl/Parquet/xsimd_wrapper.h
change compile level int xsimd_wrapper.h to use xsimd plugin.
> Add comile ignored Wcast-qual in xsimd_wrapper.h
